pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Seth Hendrick
title: Troop 53 Stories
description: "Stories from alumni of Troop 53 of Castleton, NY"
url: https://troop53stories.shendrick.net
urlnohttp: troop53stories.shendrick.net
contact: seth@shendrick.net

github: https://github.com/xforever1313/troopstories.shendrick.net
githubissues: https://github.com/xforever1313/troopstories.shendrick.net/issues

disqus_shortname: troop53stories

# ActivtyPub:
actpub_directory: "activitypub"
actpub_outbox: true
actpub_inbox: true
actpub_profileurl: posts.html
actpub_username: posts
actpub_icon: "https://www.roclongboarding.info/static/img/bsalogo.jpg"
actpub_created: "2015-12-19T00:00:00.0000000Z"
actpub_summary: "I post whenever there's a new post on Troop 53 Stories, the site that has stories from alumni of Troop 53 in Castleton, NY!"
actpub_publickeyfile: "activitypub/public.pem"
actpub_following:
 - "https://www.roclongboarding.info/activitypub/profile.json"
 - "https://tech.lgbt/users/xforever1313"

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - tools
 - .timeline.txt
 - README.md