pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Seth Hendrick
title: Troop 53 Stories
url: https://troop53stories.shendrick.net
contact: seth@shendrick.net